name: auto sync reference
on:
  schedule:
    - cron: '0 0 */3 * *' # 定时任务
  workflow_dispatch:       # 手动运行

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
        with:
          ref: 'main'
          repository: 'jaywcjlove/reference'

      - name: Build
        run: |
          y=`date +%Y`
          echo -e 'REF_URL=https://reference.guoxudong.io/\nREF_LABEL=网站首页\nLICENSE=Copyright (c) <b>'$y'</b> guoxudong.io' > .env
          npm install
          npm run build
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: reference.guoxudong.io
